package com.nht.gif

import com.nht.gif.MyConstants.ADD_TEXT_RENDER_PNG_PATH
import com.nht.gif.model.ExportColorFilter
import com.nht.gif.model.ExportLoopMode
import com.nht.gif.model.WebpQuality
import com.nht.gif.MyConstants.FFMPEG_COMMAND_PREFIX_FOR_ALL_AN
import com.nht.gif.MyConstants.OUTPUT_GIF_TEMP_PATH
import com.nht.gif.MyConstants.OUTPUT_WEBP_TEMP_PATH
import com.nht.gif.toolbox.MediaTools.saveToPng
import java.io.Serializable
import kotlin.math.ceil
import kotlin.math.min

/**
 * Immutable command-builder for a video-to-GIF (or Animated WebP) export task.
 *
 * Bundles [VideoInput] (source facts) and [ExportConfig] (output settings), and produces the
 * FFmpeg shell commands for each stage of the encoding pipeline.
 *
 * Construction triggers an [init] block that renders the optional text overlay from
 * [ExportConfig.textRender] to a PNG file on disk; every subsequent command references that PNG.
 * The pure command-builder logic lives in [Companion] static functions so it can be tested
 * independently without touching the filesystem.
 */
data class TaskBuilderVideoToGif(
  val input: VideoInput,
  val config: ExportConfig,
  /** Whether the trim end point was adjusted by Smart Trim detection. Stored for provenance;
   *  the actual trim is already baked into [VideoInput.trimTime] by the time this object is
   *  constructed. */
  val smartTrim: Boolean = false,
) : Serializable {

  init {
    TextRender.render(config.textRender, input.videoWH.first, input.videoWH.second)
      .saveToPng(ADD_TEXT_RENDER_PNG_PATH)
  }

  /**
   * Returns a lightweight [TaskBuilderVideoToGifForPreview] containing only the parameters needed
   * by the in-app preview renderer, avoiding the overhead of a full task object.
   */
  fun getForPreviewOnly() = TaskBuilderVideoToGifForPreview(
    config.shortLength, config.colorQuality, config.lossy, input.videoWH, config.colorKey, config.colorFilter
  )

  /**
   * Returns the estimated number of output frames computed from the trimmed duration, fps,
   * and output speed. Used to track encoding progress.
   */
  fun getOutputFramesEstimated() = ceil(
    (input.trimTime?.let { it.second - it.first } ?: input.duration) *
      config.fps / config.outputSpeed / 1000.0
  ).toInt()

  /**
   * Builds the FFmpeg command that extracts frames from the source video into individual BMP files,
   * applying speed, frame rate, crop, resolution, loop mode, text overlay, and colour-key filters.
   */
  fun getCommandExtractFrame(): String = buildExtractFrameCommand(
    inputVideoPath = input.path,
    textRenderPath = ADD_TEXT_RENDER_PNG_PATH,
    trimTime = input.trimTime,
    outputSpeed = config.outputSpeed,
    outputFps = config.fps,
    cropParams = input.cropParams,
    shortLength = config.shortLength,
    colorKey = config.colorKey,
    loopMode = config.loopMode,
    outputFramesPath = MyConstants.VIDEO_TO_GIF_EXTRACTED_FRAMES_PATH,
  )

  /**
   * Builds the FFmpeg command that analyses the extracted BMP frames and generates an optimised
   * GIF palette file at [MyConstants.PALETTE_PATH].
   */
  fun getCommandCreatePalette(): String = buildPaletteCommand(
    framesPath = MyConstants.VIDEO_TO_GIF_EXTRACTED_FRAMES_PATH,
    colorQuality = config.colorQuality,
    palettePath = MyConstants.PALETTE_PATH,
    colorFilter = config.colorFilter,
  )

  /**
   * Builds the FFmpeg command that assembles the extracted BMP frames into a final GIF file using
   * the palette generated by [getCommandCreatePalette].
   */
  fun getCommandVideoToGif(): String = buildGifCommand(
    framesPath = MyConstants.VIDEO_TO_GIF_EXTRACTED_FRAMES_PATH,
    palettePath = MyConstants.PALETTE_PATH,
    outputPath = OUTPUT_GIF_TEMP_PATH,
    fps = config.fps,
    finalDelay = config.finalDelay,
    colorFilter = config.colorFilter,
  )

  /**
   * Builds the FFmpeg command that assembles the extracted BMP frames into a final Animated WebP
   * file. Requires [ExportConfig.webpQuality] to be non-null; throws [IllegalStateException] otherwise.
   */
  fun getCommandVideoToWebp(): String = buildWebpCommand(
    framesPath = MyConstants.VIDEO_TO_GIF_EXTRACTED_FRAMES_PATH,
    outputPath = OUTPUT_WEBP_TEMP_PATH,
    fps = config.fps,
    quality = checkNotNull(config.webpQuality) { "webpQuality must be set when outputFormat == ANIMATED_WEBP" },
    vfChain = config.colorFilter.vfChain,
  )

  companion object {
    /**
     * Computes the FFmpeg `-vf scale=` segment that constrains the output to [shortLength] pixels
     * on the short side. Returns an empty string when [shortLength] is 0 or already at or above
     * the source resolution (no downscaling needed).
     */
    internal fun resolutionParams(cropParams: CropParams, shortLength: Int): String {
      val short = cropParams.shortLength()
      val pixel = min(shortLength, short)
      return if (shortLength == 0 || shortLength >= short) {
        ""
      } else {
        ",scale=" + if ((cropParams.outW > cropParams.outH)) {
          "-2:$pixel"
        } else {
          "$pixel:-2"
        } + ":flags=lanczos"
      }
    }

    /**
     * Pure function that builds the frame-extraction FFmpeg command. Extracted from the instance
     * method so it can be unit-tested without constructing a [TaskBuilderVideoToGif], which would
     * trigger the `init` block's file I/O.
     */
    internal fun buildExtractFrameCommand(
      inputVideoPath: String,
      textRenderPath: String,
      trimTime: Pair<Int, Int>?,
      outputSpeed: Float,
      outputFps: Int,
      cropParams: CropParams,
      shortLength: Int,
      colorKey: Pair<String, Int>?,
      loopMode: ExportLoopMode,
      outputFramesPath: String,
    ): String {
      val trimArg = trimTime?.let { "-ss ${it.first}ms -to ${it.second}ms " } ?: ""
      val colorKeyArg = colorKey?.let { ",colorkey=#${it.first}:${it.second / 100f}:0" } ?: ""
      val baseChain = "[0vPreprocessed][1:v] overlay=0:0," +
        cropParams.toFFmpegCropCommand() + resolutionParams(cropParams, shortLength) + colorKeyArg
      val (filterTail, mapArg) = when (loopMode) {
        ExportLoopMode.FORWARD -> "" to ""
        ExportLoopMode.REVERSE -> ",reverse" to ""
        ExportLoopMode.BOOMERANG ->
          "[base]; [base]split[v1][v2]; [v2]reverse[v2r]; [v1][v2r]concat=n=2:v=1:a=0[out]" to "-map \"[out]\" "
      }
      return "$FFMPEG_COMMAND_PREFIX_FOR_ALL_AN $trimArg-i \"$inputVideoPath\" -i \"$textRenderPath\" " +
        "-filter_complex \"[0:v] setpts=PTS/$outputSpeed,fps=fps=$outputFps [0vPreprocessed]; $baseChain$filterTail\" " +
        "${mapArg}\"${outputFramesPath}%06d.bmp\""
    }

    /**
     * Pure function that builds the palette-generation FFmpeg command. Extracted from the instance
     * method so it can be unit-tested without constructing a [TaskBuilderVideoToGif].
     */
    internal fun buildPaletteCommand(framesPath: String, colorQuality: Int, palettePath: String, colorFilter: ExportColorFilter): String {
      val vfPrefix = colorFilter.vfChain?.let { "$it," } ?: ""
      val maxColors = if (colorFilter == ExportColorFilter.VINTAGE) 64 else colorQuality
      return "$FFMPEG_COMMAND_PREFIX_FOR_ALL_AN -i \"${framesPath}%06d.bmp\" " +
        "-vf ${vfPrefix}palettegen=max_colors=${maxColors}:stats_mode=diff -y \"$palettePath\""
    }

    /**
     * Pure function that builds the GIF-encoding FFmpeg command. Extracted from the instance
     * method so it can be unit-tested without constructing a [TaskBuilderVideoToGif].
     */
    internal fun buildGifCommand(framesPath: String, palettePath: String, outputPath: String, fps: Int, finalDelay: Int, colorFilter: ExportColorFilter): String {
      val filterComplex = colorFilter.vfChain?.let {
        "\"[0:v]$it[v];[v][1:v]paletteuse=dither=bayer\""
      } ?: "paletteuse=dither=bayer"
      return "$FFMPEG_COMMAND_PREFIX_FOR_ALL_AN -framerate $fps " +
        "-i \"${framesPath}%06d.bmp\" -i \"$palettePath\" " +
        "-filter_complex $filterComplex -final_delay $finalDelay -y \"$outputPath\""
    }

    /**
     * Pure function that builds the Animated WebP encoding FFmpeg command. Extracted from the
     * instance method so it can be unit-tested without constructing a [TaskBuilderVideoToGif].
     */
    internal fun buildWebpCommand(framesPath: String, outputPath: String, fps: Int, quality: WebpQuality, vfChain: String? = null): String {
      val qualityFlags = if (quality.lossless) "-lossless 1" else "-quality ${quality.ffmpegQuality}"
      val vfArg = vfChain?.let { "-vf \"$it\" " } ?: ""
      return "$FFMPEG_COMMAND_PREFIX_FOR_ALL_AN -framerate $fps " +
        "-i \"${framesPath}%06d.bmp\" ${vfArg}$qualityFlags -compression_level 6 -loop 0 -y \"$outputPath\""
    }
  }
}
